### ISSUE TITLE
试用了下，可以下载下来，但是遇到几个问题。

### ISSUE THREAD

**Issue by peinhu** [ilvsx/laracasts-craw#1]
一开始运行报了个SSL致命错误，cURL error 60 : SSL certificate problem: self signed certificate in certificate chain
下载没有进度显示，就这么等着，无法知道有没有在下载，什么时候完成，如果下载中途断开，不完整的文件和完整的文件貌似看不出差别。
下载的文件是标清的吗，我记得视频分标清和高清两种，可以自主选择就好了。
最好提供下载整个Series的方法，就不用去一个一个复制视频链接了，只要填一个Series地址，就自动下载其下所有视频。
不挂SS无法下载，会报超时错误。

**Comment by ilvsx** [comment]
下载报错的问题，因为 Laracasts 存放视频的网站是被墙了的，所以还是要挂代理才能下的……
